name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            sudo -u www-data bash -c '
              cd /var/www/best_project &&
              git pull origin main &&
              composer install --no-dev --optimize-autoloader &&
              php artisan down || true &&
              php artisan config:clear &&
              php artisan route:clear &&
              php artisan view:clear &&
              php artisan cache:clear &&
              php artisan migrate --force &&
              php artisan config:cache &&
              php artisan route:cache &&
              php artisan view:cache &&
              php artisan up
            '
          "